"""add image_url to books

Revision ID: 1ab8aa8b6999
Revises: a5beae8f388a
Create Date: 2026-06-30 16:30:19.260329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ab8aa8b6999'
down_revision: Union[str, Sequence[str], None] = 'a5beae8f388a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('image_url', sa.Text(), nullable=True))
    op.drop_column('books', 'links')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('links', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('books', 'image_url')
    # ### end Alembic commands ###
