"""Add new status and types to notifications

Revision ID: eb3e994c6af2
Revises: df45ffafe6fe
Create Date: 2026-07-02 00:46:41.557575

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb3e994c6af2"
down_revision: Union[str, Sequence[str], None] = "df45ffafe6fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE notification_type ADD VALUE 'BOOK_RETURN_ACCEPTED';")
    op.execute("ALTER TYPE notification_type ADD VALUE 'BOOK_RETURN_REJECTED';")
    op.execute("ALTER TYPE notification_status ADD VALUE 'SEEN';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
